apiVersion: v1
kind: Config
preferences: {}
current-context: minikube
users:
- name: minikube
  user:
    client-certificate: /Users/abhishekghosh/.minikube/profiles/minikube/client.crt
    client-key: /Users/abhishekghosh/.minikube/profiles/minikube/client.key
clusters:
- cluster:
    certificate-authority: /Users/abhishekghosh/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Wed, 08 Mar 2023 11:53:26 IST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: cluster_info
    server: https://127.0.0.1:49154
  name: minikube
contexts:
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Wed, 08 Mar 2023 11:53:26 IST
        provider: minikube.sigs.k8s.io
        version: v1.29.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
