FROM ubuntu:16.04
RUN apt-get update
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get install -y python3
RUN apt-get install -y python3-pip
RUN apt-get update
RUN pip3 install jinja2
RUN pip3 install MarkupSafe
RUN pip3 install flask
COPY app.py /opt/simple_flask_webapp/
ENTRYPOINT FLASK_APP=/opt/simple_flask_webapp/app.py flask run --host=0.0.0.0 --port=8080
