replicaCount: 2

image:
  repository: jenkins/jenkins
  tag: lts
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: jenkins.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

serviceAccount:
  create: true
  name: jenkins

rbac:
  create: true

persistence:
  enabled: true
  hostPath: /mnt/data/jenkins
  storageClassName: standard
  reclaimPolicy: Delete
  size: 10Gi
  accessModes:
    - ReadWriteMany