# Usage: make run_c FILE=ipclass.c
c:
	gcc ./codes/$(FILE) -o ./out/$(basename $(FILE)) && ./out/$(basename $(FILE))

# Usage: make run_cpp FILE=ipclass.cpp
cpp:
	g++ ./codes/$(FILE) -o ./out/$(basename $(FILE)) && ./out/$(basename $(FILE))