apiVersion: v1
kind: Pod
metadata:
  name: postgres-client
spec:
  containers:
    - name: postgres-client
      image: postgres:latest
      command: ["sleep", "infinity"]
      resources:
        requests:
          memory: "1000M"
          cpu: "1000m"
        limits:
          memory: "1000M"
          cpu: "1000m"