apiVersion: v1
kind: Pod
metadata:
  name:  multi-container-pod
  namespace: default
  labels:
    app: multi-container-pod
spec:
  containers:
    - name: skaha-desktop-app
      image: nginx
      volumeMounts:
      - name: token-volume
        mountPath: "${access_token_path}"
        readOnly: true
    - name: token-fetcher-script-with-golang
      image: redis
      volumeMounts:
      - name: token-volume
        mountPath: "${access_token_path}"
  initContainers:
  - name: setup
    image: busybox
    command: ["sh", "-c", "echo '${access_token}' > ${access_token_path}/${access_token_file}"]
    volumeMounts:
    - name: token-volume
      mountPath: ${access_token_path}
  volumes:
  - name: token-volume
    emptyDir: {}
