version: '3.8'

services:
  jenkins:
    image: abhishek1009/jenkins
    container_name: jenkins
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"       # Jenkins UI
      - "50000:50000"     # For connecting Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /Users/abhishekghosh/.colima/default/docker.sock:/var/run/docker.sock  # Optional: Allow Jenkins to run Docker
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net: